Use Python;

-- 1/ Revenue generated by Gender
Select gender,
       Sum(purchase_amount) As Total_Revenue
From Customer_Behavior
Group By gender
Order By Total_Revenue Desc


--- Percentage of sales per gender
Select gender,
      -- Sum(purchase_amount) As Total_Revenue,
       Cast(Round(Sum(purchase_amount) * 100.0 /
    (Select Sum(purchase_amount)
    From Customer_Behavior),1) As Decimal(5,1)) As Per_Of_Sales
From Customer_Behavior
Group By gender
Order By Per_Of_Sales


--Percentage of sales by gender with discount applied
Select gender, discount_applied,
       Cast(Round(Sum(purchase_amount) * 100.0/
       (Select Sum(purchase_amount) From Customer_Behavior), 1) As Decimal(5,1)) As Per_Of_Sales
From Customer_Behavior
Group By gender, discount_applied
Order By Per_Of_Sales Desc

Select Sum(purchase_amount) As T_R
From Customer_Behavior
where discount_applied = 'Yes' and gender = 'Feamale'

--2/ Which customers used a discount but still spent more than the average purchase amount?
Select 
      customer_id,
      discount_applied,
      Sum(purchase_amount) As Total_Revenue
From Customer_Behavior 
Where (discount_applied) = 'Yes'
Group By customer_id,
      discount_applied
Having Sum(purchase_amount) >
(Select Avg(purchase_amount) As Avg_purchase_amount
From Customer_Behavior)
Order By Total_Revenue Desc;

-- 3/ Which are the top 5 products with the highest average review rating?
Select top 5 item_purchased,
       Round(Avg(review_rating),2) As Avg_review_rating
From Customer_Behavior
Group By item_purchased

-- 4/ Compare the average Purchase Amounts between Standard and Express Shipping.  
 Select shipping_type,
       Avg(purchase_amount) as Avg_purch_amount
From Customer_Behavior
Where shipping_type  IN ('Standard', 'Express')
Group by shipping_type

--5/ Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. 
Select subscription_status,
       Avg(purchase_amount) as Avg_Spent,
       Sum(purchase_amount) as Total_Revenue
From Customer_Behavior
--Where subscription_status In ('Yes' , 'No')
Group By subscription_status;

--6/ Which 5 products have the highest percentage of purchases with discounts applied?
Select Top 5 item_purchased, 
       SUM(
           Case When discount_applied = 'Yes'
           Then 1 Else 0 End) * 100/ Count(*) As Per_of_disc
From Customer_Behavior
Group By item_purchased
Order By Per_of_disc Desc;

Select Top 5 item_purchased,
       SUm(
           Case When discount_applied = 'No'
           Then 1 Else 0 End) * 100 / Count(*) as  Per_of_without_disc
From Customer_Behavior
Group By item_purchased
Order By Per_of_without_disc Desc


Select gender, count(gender) As Gender_count
From Customer_Behavior
Group By gender
       

--7/ Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

With Customer_type As (
     Select customer_id, previous_purchases,
     Case
         When previous_purchases = 1 Then  'New'
         When previous_purchases Between 2 and 10 THEN 'Returning'
         Else 'Loyal'
         End As Customent_Segment
       From Customer_Behavior)
Select Customent_Segment, Count(*) As cust_number
From Customer_type
Group By Customent_Segment;

--8/  What are the top 3 most purchased products within each category?
-- CTE (Common Table Expression) used as temporary namne
With CTE As(
           Select item_purchased, category, Sum(purchase_amount) As Tota_Revenue,
           Row_Number() Over(

           Partition By category Order by Sum(purchase_amount) Desc) As Ranking
           From Customer_Behavior
           Group By item_purchased, category )

    Select item_purchased, category, Tota_Revenue, Ranking
    From CTE
    Where Ranking <= 3
    Order By Tota_Revenue Desc
 

--9/ Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
       Count(*) As Num_Cust
       From Customer_Behavior
    Where previous_purchases > 5
    Group By subscription_status
Order By Num_Cust Desc

-- 10/ What is the revenue contribution of each age group? 
Select age_group, Sum(purchase_amount) As total_Revenue
From Customer_Behavior
Group By age_group

     Select * From Customer_Behavior; 





Select count(distinct customer_id) From Customer_Behavior; 
